[package]
name = "fuzzy-img-viewer-backend"
version = "0.1.4"
edition = "2021"

[[bin]]
name = "fuzzy-img-viewer-backend"
path = "src/main.rs"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "cors", "trace"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
image = "0.24"
rayon = "1.10"
walkdir = "2"
ignore = "0.4"
chrono = "0.4"
regex = "1"
sha2 = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "5.0"
mime_guess = "2.0"
urlencoding = "2.1"
